# Generated by Django 5.1.1 on 2024-09-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": [
                    ("can_view_hr_dashboard", "Can view HR dashboard"),
                    ("can_view_employee_dashboard", "Can view Employee dashboard"),
                    ("can_view_team_lead_dashboard", "Can view Team Lead dashboard"),
                ]
            },
        ),
    ]
