# Generated by Django 5.1.1 on 2024-10-01 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_department_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Timesheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("application_name", models.CharField(max_length=255)),
                ("task_title", models.CharField(max_length=255)),
                ("task_description", models.TextField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("hours_spent", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "percent_completed",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("total_efforts", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
