# Generated by Django 5.1.1 on 2024-10-01 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_leaverequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="employee",
            name="education",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="remaining_leaves_month",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="remaining_leaves_year",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="employee",
            name="salary_slip_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="employee",
            name="team_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_lead",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
