# Generated by Django 5.1.1 on 2024-10-04 06:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_employee_address_employee_education_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timesheet",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                ],
                default="Submitted",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="timesheet",
            name="submit_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
